"""Database helpers for encrypted local storage."""

from .auth import (
    Account,
    AccountExistsError,
    AuthenticationError,
    AuthorizationError,
    BUILT_IN_ADMIN_USERNAME,
    authenticate_account,
    delete_account,
    create_initial_admin_account,
    create_psychologist_account,
    ensure_built_in_admin_account,
    has_admin_account,
    is_psychologist_authorized,
    list_accounts,
    update_account,
)
from .database import (
    DB_KEY_ENV_VAR,
    DB_PATH_ENV_VAR,
    DatabaseInitializationError,
    InvalidDatabaseKeyError,
    MissingDatabaseKeyError,
    connect_encrypted,
    initialize_database,
    is_sqlite_header,
    resolve_db_path,
)
from .records import (
    ClientProfile,
    RecordCounts,
    SessionRecord,
    create_client_profile,
    create_session_record,
    delete_client_profile,
    delete_session_record,
    get_record_counts,
    list_client_profiles,
    list_session_records,
)

__all__ = [
    "Account",
    "AccountExistsError",
    "AuthenticationError",
    "AuthorizationError",
    "BUILT_IN_ADMIN_USERNAME",
    "authenticate_account",
    "delete_account",
    "create_initial_admin_account",
    "create_psychologist_account",
    "ensure_built_in_admin_account",
    "has_admin_account",
    "is_psychologist_authorized",
    "list_accounts",
    "update_account",
    "DB_KEY_ENV_VAR",
    "DB_PATH_ENV_VAR",
    "DatabaseInitializationError",
    "InvalidDatabaseKeyError",
    "MissingDatabaseKeyError",
    "connect_encrypted",
    "initialize_database",
    "is_sqlite_header",
    "resolve_db_path",
    "ClientProfile",
    "RecordCounts",
    "SessionRecord",
    "create_client_profile",
    "create_session_record",
    "delete_client_profile",
    "delete_session_record",
    "get_record_counts",
    "list_client_profiles",
    "list_session_records",
]
