[project]
name = "stat405-audionotetaker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain-text-splitters>=1.1.1",
    "llama-cpp-python>=0.3.16",
    "pyside6>=6.10.2",
    "sqlcipher3>=0.6.2",
    "transcribe-anything>=3.2.4",
]
