[project]
name = "stat405-audionotetaker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dataclasses>=0.8",
    "datasets[audio]>=4.7.0",
    "faster-whisper>=1.2.1",
    "ipykernel>=7.2.0",
    "iso639-lang>=2.6.3",
    "jiwer>=4.0.0",
    "langchain-text-splitters>=1.1.1",
    "levenshtein>=0.27.3",
    "numpy>=2.4.2",
    "pathlib>=1.0.1",
    "pip>=26.0.1",
    "pydantic-settings>=2.13.1",
    "pyside6>=6.10.2",
    "pytest>=9.0.2",
    "pytest-qt>=4.5.0",
    "scikit-learn>=1.8.0",
    "sqlcipher3>=0.6.2",
    "torch>=2.8.0",
    "torchaudio>=2.8.0",
    "transformers>=4.57.6",
    "typing>=3.10.0.0",
    "werpy>=3.3.0",
    "whisperx>=3.8.1",
]

[project.optional-dependencies]
local-llm = [
    "llama-cpp-python>=0.3.16",
]
