"""Prove DB write/read/delete flow for a psychologist account without GUI."""

from __future__ import annotations

import argparse
import getpass
from datetime import datetime, timezone
from pathlib import Path
import sys

ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from app.db import (
    AuthenticationError,
    AuthorizationError,
    InvalidDatabaseKeyError,
    MissingDatabaseKeyError,
    authenticate_account,
    create_client_profile,
    create_session_record,
    delete_client_profile,
    delete_session_record,
    get_record_counts,
    initialize_database,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--username",
        required=True,
        help="Psychologist username to run the proof against",
    )
    parser.add_argument(
        "--keep-created",
        action="store_true",
        help="Keep created proof client/session instead of deleting them",
    )
    return parser.parse_args()


def _timestamp_token() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")


def main() -> int:
    args = parse_args()
    try:
        initialize_database()
    except MissingDatabaseKeyError:
        print("[ERROR] No database key found for this machine.")
        print(
            "[HINT] Launch the app once and set/unlock the local DB password, then retry."
        )
        return 1
    except InvalidDatabaseKeyError:
        print("[ERROR] Could not decrypt the local database with available keys.")
        print(
            "[HINT] If you changed passwords before, clear old TRANSCRIBENOTES_DB_KEY and retry."
        )
        return 1

    password = getpass.getpass("Psychologist password: ")
    try:
        account = authenticate_account(args.username, password)
    except AuthenticationError as exc:
        print(f"[ERROR] {exc}")
        return 1

    if account.role != "psychologist":
        print("[ERROR] This script only supports psychologist accounts.")
        return 1

    try:
        before = get_record_counts(account.id)
    except AuthorizationError as exc:
        print(f"[ERROR] {exc}")
        return 1

    token = _timestamp_token()
    client = create_client_profile(
        psychologist_account_id=account.id,
        client_code=f"PROOF-{token}",
        first_name="Proof",
        last_name="Client",
        notes="Auto-generated by scripts/prove_db_roundtrip.py",
    )
    session = create_session_record(
        psychologist_account_id=account.id,
        client_profile_id=client.id,
        source_audio_path=f"proof://session-{token}.mp4",
        detected_language="en",
        transcript_text="Proof transcript payload",
        summary_text="Proof summary payload",
    )

    after_insert = get_record_counts(account.id)

    print("[STEP] Counts before insert")
    print(f"  clients={before.client_count}, sessions={before.session_count}")
    print("[STEP] Inserted proof records")
    print(f"  client_id={client.id}, session_id={session.id}, client_code={client.client_code}")
    print("[STEP] Counts after insert")
    print(
        f"  clients={after_insert.client_count}, sessions={after_insert.session_count}"
    )

    if args.keep_created:
        print("[DONE] Keeping inserted proof records (--keep-created set).")
        return 0

    deleted_session = delete_session_record(
        psychologist_account_id=account.id,
        session_record_id=session.id,
    )
    deleted_client = delete_client_profile(
        psychologist_account_id=account.id,
        client_profile_id=client.id,
    )
    after_delete = get_record_counts(account.id)

    print("[STEP] Deleted proof records")
    print(f"  session_deleted={deleted_session}, client_deleted={deleted_client}")
    print("[STEP] Counts after delete")
    print(
        f"  clients={after_delete.client_count}, sessions={after_delete.session_count}"
    )

    if (before.client_count, before.session_count) != (
        after_delete.client_count,
        after_delete.session_count,
    ):
        print("[WARN] Final counts differ from initial counts.")
        return 2

    print("[DONE] Round-trip proof complete: insert/read/delete succeeded.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
